name: Deploy FastAPI App to EC2

on:
  push:
    branches: [ "pankti-master" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: cd iac && terraform init

      - name: Terraform Apply
        run: cd iac && terraform apply -auto-approve

      - name: Get EC2 IP from Terraform Output
        id: tf_output
        env:
          TERRAFORM_CLI_PATH: ""
          TERRAFORM_LOG: ""
        run: |
          IP=$(cd iac && terraform output -raw instance_ip 2>/dev/null | tr -d '\r\n' | head -n1)
          echo "EC2 Public IP: $IP"
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/pankti-capstone.pem
          chmod 400 ~/.ssh/pankti-capstone.pem

      - name: Test SSH Connection
        run: |
          IP="${{ steps.tf_output.outputs.ip }}"
          echo "Testing SSH to ubuntu@$IP"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/pankti-capstone.pem ubuntu@$IP "echo ✅ SSH connection successful"

      - name: Deploy App to EC2
        run: |
          IP="${{ steps.tf_output.outputs.ip }}"
          echo "Copying backend files to EC2..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/pankti-capstone.pem -r Project/backend/src/* ubuntu@$IP:/home/ubuntu/

          echo "Installing dependencies and launching app..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/pankti-capstone.pem ubuntu@$IP <<EOF
            sudo apt update
            sudo apt install -y python3-pip
            sudo pip3 install -r /home/ubuntu/requirements.txt
            cd /home/ubuntu/
            nohup uvicorn backend.src.main:app --host 0.0.0.0 --port 80 &
          EOF

      - name: Done
        run: echo "FastAPI app deployed successfully to ${{ steps.tf_output.outputs.ip }}"
