name: Deploy FastAPI App to EC2

on:
  push:
    branches: [ "pankti-master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: cd iac && terraform init

      - name: Terraform Apply
        run: cd iac && terraform apply -auto-approve

      # 🔐 Setup SSH Key for EC2 Access
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/pankti-capstone.pem
          chmod 400 ~/.ssh/pankti-capstone.pem
          echo "📄 SSH Key preview:"
          head -n 5 ~/.ssh/pankti-capstone.pem
          ls -la ~/.ssh

      # 🌐 Export EC2 Public IP from Terraform
      - name: Export EC2 IP to Env
        run: |
          IP=$(cd iac && terraform output -raw instance_ip | head -n1 | tr -d '[:space:]')
          echo "IP=$IP" >> $GITHUB_ENV

      # 🧪 Test SSH Connection
      - name: Test SSH Connection
        run: |
          echo "Testing SSH to ubuntu@${{ env.IP }}"
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/pankti-capstone.pem ubuntu@${{ env.IP }} "echo ✅ SSH connection successful"

      # 🚀 Deploy FastAPI App
      - name: Deploy App to EC2
        run: |
          echo "📁 Copying backend files to EC2..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/pankti-capstone.pem -r Project/backend/src/* ubuntu@$IP:/home/ubuntu/

          echo "⚙️ Installing dependencies and launching app..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/pankti-capstone.pem ubuntu@$IP <<'EOF'
            sudo apt update
            sudo apt install -y python3-pip
            sudo pip3 install -r /home/ubuntu/requirements.txt
            cd /home/ubuntu/
            nohup uvicorn backend.src.main:app --host 0.0.0.0 --port 80 &
          EOF

      - name: Done ✅
        run: echo "🎉 FastAPI app deployed successfully to $IP"
